### ISSUE TITLE
About transmil

### ISSUE THREAD

**Issue by akidway** [lingxitong/MIL_BASELINE#1]
Hi, @lingxitong 
Thank you for your contribute.

I wander have you ever run transmil? If so, did you get a best result among dsmil and abmil?

Since articles reported transmil always get a better than dsmil and abmil. But I still can't get the same of articles report.

Looking for your reply.

**Comment by akidway** [comment]
May be I got reason, transmil used best fold result on test as final result.
While I used best val set model then test on test set.

**Comment by lingxitong** [comment]
> May be I got reason, transmil used best fold result on test as final result. While I used best val set model then test on test set.

hello,you can see https://github.com/lingxitong/MIL_BASELINE/issues/1#issuecomment-2130665214 different Dataset split may lead different results , but fair comparison is really need.

**Comment by lingxitong** [comment]
> May be I got reason, transmil used best fold result on test as final result. While I used best val set model then test on test set.

hello,you can see  https://github.com/lingxitong/MIL_BASELINE different Dataset split may lead different results , but fair comparison is really need.
