### ISSUE TITLE
Missing multi loss implementation?

### ISSUE THREAD

**Issue by akidway** [lingxitong/MIL_BASELINE#2]
Hi, 

Thank you for your work,

I'm worried that there might be something missing for multi-loss implementation, (e.g. clam which has a bag loss and a instance loss), in the code you shared. (https://github.com/lingxitong/MIL_BASELINE/blob/47c45d0abc4714375a0552d490264ded248e2482/utils/loop_utils.py#L56) 
Could you help me double-check?

**Comment by lingxitong** [comment]
thanks ,i will update
