### ISSUE TITLE
热力图生成问题

### ISSUE THREAD

**Issue by rssqbjn** [lingxitong/MIL_BASELINE#7]
文件feature_extractor/CLAM/vis_utils/heatmap_utils.py的第77行
A[score_idx] = score2percentile(A[score_idx], ref_scores)  之前是否应该先将ref_scores转换成一维数组呢，现在在运行时会在该地方出现ValueError: could not broadcast input array from shape (5989,) into shape (1,)

**Comment by lingxitong** [comment]
hello,this is the bug in CLAM,you can find the solution in CLAM issues

**Comment by jermmy19998** [comment]
squeeze一下
