### ISSUE TITLE
multi-gpu training

### ISSUE THREAD

**Issue by AlexNmSED** [lingxitong/MIL_BASELINE#8]
Hello, is it possible to update the version for multi-GPU training?

**Comment by lingxitong** [comment]
Hello，We will update several new functions including Multi-Gpu training next week.Thanks for your attention to MIL_BASELINE

**Comment by AlexNmSED** [comment]
Thank you for your help.
This is a great work. I will share it with my friends.

**Comment by AlexNmSED** [comment]
Hello, when will the update be available?  Thank you
